# Generated by Django 4.0 on 2022-01-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rav_app.position')),
            ],
        ),
    ]
