# Generated by Django 4.0 on 2021-12-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Redbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=20)),
                ('passenger_id', models.CharField(max_length=20)),
                ('where', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=30)),
                ('bus_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redbus_app.position')),
            ],
        ),
    ]
