# Generated by Django 4.0 on 2021-12-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='XYZ',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.CharField(max_length=20)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xyz_app.position')),
            ],
        ),
    ]
