# Generated by Django 4.0 on 2022-01-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=50)),
                ('blog_image', models.ImageField(upload_to='blog_images')),
                ('blog_desc', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('publisher_name', models.CharField(max_length=50)),
            ],
        ),
    ]
