# Generated by Django 4.0 on 2021-12-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zing',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
    ]
