# Generated by Django 4.0 on 2022-01-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=1000)),
                ('Image', models.ImageField(upload_to='Family_images')),
                ('Food', models.CharField(max_length=100)),
                ('Publicity', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=12)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField(max_length=1400)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=1000)),
                ('Image', models.ImageField(upload_to='Family_images')),
                ('Food', models.CharField(max_length=100)),
                ('Decorations', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=1000)),
                ('Image', models.ImageField(upload_to='Family_images')),
                ('Food', models.CharField(max_length=100)),
                ('CG', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=1000)),
                ('Image', models.ImageField(upload_to='Family_images')),
                ('Food', models.CharField(max_length=100)),
                ('Decorations', models.CharField(max_length=1000)),
                ('CG', models.CharField(max_length=1000)),
                ('Sponcer', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bookevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=12)),
                ('Location', models.CharField(max_length=100)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('People', models.IntegerField(default='')),
                ('Date', models.DateField()),
                ('Event', models.CharField(max_length=100)),
                ('Food', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=400)),
                ('Message', models.CharField(max_length=400)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
