# Generated by Django 4.0 on 2022-01-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('age', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
